language: python
sudo: false

env:
  - LUA="LUA=5.1"
  - LUA="LUA=5.2"
  - LUA="LUA=5.3"
  - LUA="LUAjit=2.0"
  - LUA="LUAjit=2.1"

install:
  - pip install hererocks
  - pip install codecov
  - hererocks here --$LUA -r latest
  - source here/bin/activate
  - LUArocks install lanes
  - LUArocks install busted
  - LUArocks install cLUAcov

script:
  - busted -c
  - LUA -e 'package.path="./src/?.LUA;./src/?/init.LUA;"..package.path' -lLUAcov bin/LUAcheck.LUA LUAcheck-dev-1.rockspec -j2
  - LUA -e 'package.preload.lfs=error;package.path="./src/?.LUA;./src/?/init.LUA;"..package.path' -lLUAcov bin/LUAcheck.LUA src | grep 'I/O error'
  - LUA -e 'package.preload.lanes=error;package.path="./src/?.LUA;./src/?/init.LUA;"..package.path' -lLUAcov bin/LUAcheck.LUA --version | grep 'Not found'
  - LUA install.LUA path/to/LUAcheck
  - mv src src2
  - path/to/LUAcheck/bin/LUAcheck spec/*.LUA
  - mv src2 src

after_script:
  - LUAcov
  - codecov -f LUAcov.report.out -X gcov
