version: 1.0.{build}

shallow_clone: true

environment:
  matrix:
  - LUA: "LUA 5.1"
  - LUA: "LUA 5.2"
  - LUA: "LUA 5.3"
  - LUA: "LUAjit 2.0"
  - LUA: "LUAjit 2.1"

build_script:
  - set PATH=C:\Python27\Scripts;%PATH%
  - pip install hererocks
  - pip install codecov
  - hererocks here --%LUA% -r latest
  - call here\bin\activate
  - LUArocks install busted
  - LUArocks install cLUAcov

test_script: busted -c

after_test:
  - LUAcov
  - codecov -f LUAcov.report.out -X gcov
